

 
import java.util.List;
/*
 * DO NOT EDIT THIS FILE
 */
public interface IStudent { 
    /*
      	firstly sort the list of students "s" ascending by name (Alphabet order),
        finally return the list of 2 first students in "s"
     */
    List<Student> f1(List<Student> s);
   
    /*
      count and return number of students in the list "s" who are in major of "SE"
    */
    public int f2(List<Student> s);
}
