// ======= DO NOT EDIT THIS FILE ============
public class Lamp
 {String type;
  int color,price;
  Lamp(String xType, int xColor, int xPrice)
   {type=xType;color=xColor;price=xPrice;
   }
  public String toString()
   {return("(" +type+","+color + "," + price + ")");
   }
 }
