/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javadesk_p0011;

import javax.swing.JButton;

/**
 *
 * @author tuans
 */
public class MyCalculator extends javax.swing.JFrame {

    /**
     * Creates new form MyCalculator
     */
    Boolean newOperator=true;
    String operation=null;
    double result;
    public MyCalculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        txtScreen = new javax.swing.JTextField();
        pnButton = new javax.swing.JPanel();
        bt7 = new javax.swing.JButton();
        bt8 = new javax.swing.JButton();
        bt9 = new javax.swing.JButton();
        bt4 = new javax.swing.JButton();
        bt5 = new javax.swing.JButton();
        bt6 = new javax.swing.JButton();
        bt1 = new javax.swing.JButton();
        bt2 = new javax.swing.JButton();
        bt3 = new javax.swing.JButton();
        bt0 = new javax.swing.JButton();
        btAdd = new javax.swing.JButton();
        btSub = new javax.swing.JButton();
        btMul = new javax.swing.JButton();
        btDiv = new javax.swing.JButton();
        btSolve = new javax.swing.JButton();
        btClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtScreen.setEditable(false);
        txtScreen.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtScreen.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        pnButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnButton.setLayout(new java.awt.GridBagLayout());

        bt7.setText("7");
        bt7.setMaximumSize(new java.awt.Dimension(55, 45));
        bt7.setMinimumSize(new java.awt.Dimension(55, 45));
        bt7.setPreferredSize(new java.awt.Dimension(55, 45));
        bt7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt7ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnButton.add(bt7, gridBagConstraints);

        bt8.setText("8");
        bt8.setMaximumSize(new java.awt.Dimension(55, 45));
        bt8.setMinimumSize(new java.awt.Dimension(55, 45));
        bt8.setPreferredSize(new java.awt.Dimension(55, 45));
        bt8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt8ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnButton.add(bt8, gridBagConstraints);

        bt9.setText("9");
        bt9.setToolTipText("");
        bt9.setMaximumSize(new java.awt.Dimension(55, 45));
        bt9.setMinimumSize(new java.awt.Dimension(55, 45));
        bt9.setPreferredSize(new java.awt.Dimension(55, 45));
        bt9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt9ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnButton.add(bt9, gridBagConstraints);

        bt4.setText("4");
        bt4.setMaximumSize(new java.awt.Dimension(55, 45));
        bt4.setMinimumSize(new java.awt.Dimension(55, 45));
        bt4.setPreferredSize(new java.awt.Dimension(55, 45));
        bt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnButton.add(bt4, gridBagConstraints);

        bt5.setText("5");
        bt5.setMaximumSize(new java.awt.Dimension(55, 45));
        bt5.setMinimumSize(new java.awt.Dimension(55, 45));
        bt5.setPreferredSize(new java.awt.Dimension(55, 45));
        bt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt5ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnButton.add(bt5, gridBagConstraints);

        bt6.setText("6");
        bt6.setMaximumSize(new java.awt.Dimension(55, 45));
        bt6.setMinimumSize(new java.awt.Dimension(55, 45));
        bt6.setPreferredSize(new java.awt.Dimension(55, 45));
        bt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt6ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnButton.add(bt6, gridBagConstraints);

        bt1.setText("1");
        bt1.setMaximumSize(new java.awt.Dimension(55, 45));
        bt1.setMinimumSize(new java.awt.Dimension(55, 45));
        bt1.setPreferredSize(new java.awt.Dimension(55, 45));
        bt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnButton.add(bt1, gridBagConstraints);

        bt2.setText("2");
        bt2.setMaximumSize(new java.awt.Dimension(55, 45));
        bt2.setMinimumSize(new java.awt.Dimension(55, 45));
        bt2.setPreferredSize(new java.awt.Dimension(55, 45));
        bt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnButton.add(bt2, gridBagConstraints);

        bt3.setText("3");
        bt3.setMaximumSize(new java.awt.Dimension(55, 45));
        bt3.setMinimumSize(new java.awt.Dimension(55, 45));
        bt3.setPreferredSize(new java.awt.Dimension(55, 45));
        bt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnButton.add(bt3, gridBagConstraints);

        bt0.setText("0");
        bt0.setMaximumSize(new java.awt.Dimension(55, 45));
        bt0.setMinimumSize(new java.awt.Dimension(55, 45));
        bt0.setPreferredSize(new java.awt.Dimension(55, 45));
        bt0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt0ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnButton.add(bt0, gridBagConstraints);

        btAdd.setText("+");
        btAdd.setMaximumSize(new java.awt.Dimension(55, 45));
        btAdd.setMinimumSize(new java.awt.Dimension(55, 45));
        btAdd.setPreferredSize(new java.awt.Dimension(55, 45));
        btAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 5);
        pnButton.add(btAdd, gridBagConstraints);

        btSub.setText("-");
        btSub.setMaximumSize(new java.awt.Dimension(55, 45));
        btSub.setMinimumSize(new java.awt.Dimension(55, 45));
        btSub.setPreferredSize(new java.awt.Dimension(55, 45));
        btSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSubActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 5);
        pnButton.add(btSub, gridBagConstraints);

        btMul.setText("*");
        btMul.setMaximumSize(new java.awt.Dimension(55, 45));
        btMul.setMinimumSize(new java.awt.Dimension(55, 45));
        btMul.setPreferredSize(new java.awt.Dimension(55, 45));
        btMul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMulActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 5);
        pnButton.add(btMul, gridBagConstraints);

        btDiv.setText("/");
        btDiv.setMaximumSize(new java.awt.Dimension(55, 45));
        btDiv.setMinimumSize(new java.awt.Dimension(55, 45));
        btDiv.setPreferredSize(new java.awt.Dimension(55, 45));
        btDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDivActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 5);
        pnButton.add(btDiv, gridBagConstraints);

        btSolve.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        btSolve.setText("=");
        btSolve.setMaximumSize(new java.awt.Dimension(55, 45));
        btSolve.setMinimumSize(new java.awt.Dimension(55, 45));
        btSolve.setPreferredSize(new java.awt.Dimension(55, 45));
        btSolve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSolveActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 5);
        pnButton.add(btSolve, gridBagConstraints);

        btClear.setText("Clear");
        btClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClearActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        pnButton.add(btClear, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtScreen)
                    .addComponent(pnButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(txtScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void addTextForScreen(JButton btNum){
        if (newOperator && btNum.getText().equals("0"))
            return;
        if (newOperator){
            txtScreen.setText(btNum.getText());
            newOperator=false;
        }else{
            String currentText=txtScreen.getText();
            txtScreen.setText(currentText+btNum.getText());
        }
    }
    private void bt0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt0ActionPerformed
        // TODO add your handling code here:
        addTextForScreen(bt0);
    }//GEN-LAST:event_bt0ActionPerformed

    private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1ActionPerformed
        // TODO add your handling code here:
        addTextForScreen(bt1);
    }//GEN-LAST:event_bt1ActionPerformed

    private void bt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt2ActionPerformed
        // TODO add your handling code here:
        addTextForScreen(bt2);
    }//GEN-LAST:event_bt2ActionPerformed

    private void bt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt3ActionPerformed
        // TODO add your handling code here:
        addTextForScreen(bt3);
    }//GEN-LAST:event_bt3ActionPerformed

    private void bt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt4ActionPerformed
        // TODO add your handling code here:
        addTextForScreen(bt4);
    }//GEN-LAST:event_bt4ActionPerformed

    private void bt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt5ActionPerformed
        // TODO add your handling code here:
        addTextForScreen(bt5);
    }//GEN-LAST:event_bt5ActionPerformed

    private void bt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt6ActionPerformed
        // TODO add your handling code here:
        addTextForScreen(bt6);
    }//GEN-LAST:event_bt6ActionPerformed

    private void bt7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt7ActionPerformed
        // TODO add your handling code here:
        addTextForScreen(bt7);
    }//GEN-LAST:event_bt7ActionPerformed

    private void bt8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt8ActionPerformed
        // TODO add your handling code here:
        addTextForScreen(bt8);
    }//GEN-LAST:event_bt8ActionPerformed

    private void bt9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt9ActionPerformed
        // TODO add your handling code here:
        addTextForScreen(bt9);
    }//GEN-LAST:event_bt9ActionPerformed

    void doCalculator(String op){
        if (txtScreen.getText().isEmpty())
            return;
        if (operation!=null){
            switch (operation){
                case "+":result=CalculatorLogic.add(result, Double.parseDouble(txtScreen.getText()));
                         break;
                case "-":result=CalculatorLogic.sub(result, Double.parseDouble(txtScreen.getText()));
                         break;
                case "*":result=CalculatorLogic.mul(result, Double.parseDouble(txtScreen.getText()));
                         break;
                case "/":result=CalculatorLogic.div(result, Double.parseDouble(txtScreen.getText()));
                         break;     
            }
        }else{
            result=Double.parseDouble(txtScreen.getText());
        }
        txtScreen.setText(result+"");
        newOperator=true;
        operation=op;
    }
    private void btAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddActionPerformed
        // TODO add your handling code here:
        doCalculator("+");
    }//GEN-LAST:event_btAddActionPerformed

    private void btSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSubActionPerformed
        // TODO add your handling code here:
        doCalculator("-");
    }//GEN-LAST:event_btSubActionPerformed

    private void btMulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMulActionPerformed
        // TODO add your handling code here:
        doCalculator("*");
    }//GEN-LAST:event_btMulActionPerformed

    private void btDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDivActionPerformed
        // TODO add your handling code here:
        doCalculator("/");
    }//GEN-LAST:event_btDivActionPerformed

    private void btSolveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSolveActionPerformed
        // TODO add your handling code here:
        doCalculator(null);
    }//GEN-LAST:event_btSolveActionPerformed

    private void btClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClearActionPerformed
        // TODO add your handling code here:
        txtScreen.setText("");
        newOperator=true;
        operation=null;
        result=0;
    }//GEN-LAST:event_btClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyCalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt0;
    private javax.swing.JButton bt1;
    private javax.swing.JButton bt2;
    private javax.swing.JButton bt3;
    private javax.swing.JButton bt4;
    private javax.swing.JButton bt5;
    private javax.swing.JButton bt6;
    private javax.swing.JButton bt7;
    private javax.swing.JButton bt8;
    private javax.swing.JButton bt9;
    private javax.swing.JButton btAdd;
    private javax.swing.JButton btClear;
    private javax.swing.JButton btDiv;
    private javax.swing.JButton btMul;
    private javax.swing.JButton btSolve;
    private javax.swing.JButton btSub;
    private javax.swing.JPanel pnButton;
    private javax.swing.JTextField txtScreen;
    // End of variables declaration//GEN-END:variables
}
