// ======= DO NOT EDIT THIS FILE ============
import java.io.*;
public class Main {
    
   public static void main(String args[]) throws Exception {
       
       BufferedReader in = new BufferedReader(new InputStreamReader(System.in));
       System.out.print("Enter password: ");
       String password = in.readLine();
       System.out.print("Is Admin password(yes/no): ");
       String admin = in.readLine();
       System.out.print("Enter TC: ");
       int tc = Integer.parseInt(in.readLine());
       System.out.println("OUTPUT:");
       MyPassword s = new MyPassword(password,admin.equalsIgnoreCase("yes"));
       if(tc == 1) 
           System.out.println(s);
       else if(tc == 2)
           System.out.println(s.getPassword());      
   }
 }
