
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author tuans
 */
public class BText extends javax.swing.JFrame {

    /**
     * Creates new form BText
     */
    Timer t;
    Boolean toLeft=false;
    public BText() {
        initComponents();
        initTimer();
        t.start();
    }
     String moveLeft()
    {
        String s = txtLabel.getText();
        String h = s.substring(1)+s.charAt(0);
        return(h);
    }
   String moveRight()
    {
        String s = txtLabel.getText();
        String h = s.charAt(s.length()-1) + s.substring(0,s.length()-1);
        return(h);
    }
    void lbMoveText(){
        String x;
        if(toLeft)
            x = moveLeft();
        else
            x = moveRight();
        txtLabel.setText(x);
 
    }
    void initTimer(){
        t=new Timer(500,new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                lbMoveText();
            }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        txtLabel = new javax.swing.JLabel();
        rdStart = new javax.swing.JRadioButton();
        rdStop = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtLabel.setText("Phan Anh Tuan ");

        buttonGroup1.add(rdStart);
        rdStart.setSelected(true);
        rdStart.setText("Start");
        rdStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdStartActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdStop);
        rdStop.setText("Stop");
        rdStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdStopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(rdStart)
                        .addGap(28, 28, 28)
                        .addComponent(rdStop))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(txtLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(txtLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdStart)
                    .addComponent(rdStop))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdStartActionPerformed
        // TODO add your handling code here:
        if (rdStart.isSelected()){
            t.start();
        }
        if (rdStop.isSelected()){
            t.stop();
        }
    }//GEN-LAST:event_rdStartActionPerformed

    private void rdStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdStopActionPerformed
        // TODO add your handling code here:
        if (rdStart.isSelected()){
            t.start();
        }
        if (rdStop.isSelected()){
            t.stop();
        }
    }//GEN-LAST:event_rdStopActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BText.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BText.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BText.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BText.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BText().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton rdStart;
    private javax.swing.JRadioButton rdStop;
    private javax.swing.JLabel txtLabel;
    // End of variables declaration//GEN-END:variables
}
