// ======= DO NOT EDIT THIS FILE ============
import java.io.*;
class Mainstudent {
   public static void main(String args[]) throws Exception  {
       BufferedReader in = new BufferedReader(new InputStreamReader(System.in));
       System.out.print("Enter student ID: ");
       String ID = in.readLine();
       System.out.print("Enter student name: ");
       String name = in.readLine();
       System.out.print("Enter student age: ");
       int age = Integer.parseInt(in.readLine());
       System.out.print("Enter TC: ");
       int tc = Integer.parseInt(in.readLine());
       System.out.println("OUTPUT:");
       student s = new student(ID,name,age);
       if(tc == 1) 
           System.out.println(s);
       else if(tc == 2)
           System.out.println(s.getname());
       if(tc == 3)
           System.out.println(s.getLastID());
       
   }
 }
