

 
import java.util.List;
/*
 * DO NOT EDIT THIS FILE
 */
public interface IRoom { 
    /*
      	return the list or rooms in r which have room size greater than or equals to given size 
     */
    List<Room> f1(List<Room> r, int size);
   
    /*
       set n = size of(a). 
       if n is an even number, sort rooms in the list r asceding by room name. 
       The sorting must ignores the case during comparison.
       Otherwise so rooms in the list r descending by room size.
    */
    public void f2(List<Room> r);
}
