// ======= DO NOT EDIT THIS FILE ============
import java.io.*;
class Main {
   public static void main(String args[]) throws Exception {
       BufferedReader in = new BufferedReader(new InputStreamReader(System.in));
       System.out.print("Enter name of a worker: ");
       String name = in.readLine();
       System.out.print("Enter payment rate of a worker: ");
       double rate = Double.parseDouble(in.readLine());       
       System.out.print("Enter working hours of a worker: ");
       double hours = Double.parseDouble(in.readLine());
       System.out.print("Enter TC: ");
       int tc = Integer.parseInt(in.readLine());
       System.out.println("OUTPUT:");      
       if(tc == 1) {
            Person b = new Person(name);
            System.out.println(b);
            b = new Worker(name, hours, rate);
            System.out.println(b);
       }
       else if(tc == 2) {
           Worker b = new Worker(name, hours, rate);
           System.out.println(b.getIncome());
       }
   }
 }
